"""initial schema

Revision ID: 759261d50fb5
Revises: 
Create Date: 2026-04-14 10:10:32.049266

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759261d50fb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('points_per_visit', sa.Integer(), nullable=False),
    sa.Column('reward_threshold', sa.Integer(), nullable=False),
    sa.Column('apple_pass_type_id', sa.String(length=200), nullable=True),
    sa.Column('apple_cert_s3_key', sa.String(length=500), nullable=True),
    sa.Column('apple_cert_password_encrypted', sa.String(length=500), nullable=True),
    sa.Column('google_issuer_id', sa.String(length=200), nullable=True),
    sa.Column('google_wallet_class_id', sa.String(length=200), nullable=True),
    sa.Column('google_service_account_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_locations_brand_id'), 'locations', ['brand_id'], unique=False)
    op.create_table('passes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('apple', 'google', name='pass_platform'), nullable=False),
    sa.Column('platform_pass_id', sa.String(length=500), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_passes_brand_id'), 'passes', ['brand_id'], unique=False)
    op.create_index(op.f('ix_passes_user_id'), 'passes', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', name='staff_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_brand_id'), 'staff', ['brand_id'], unique=False)
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_table('staff_locations',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'location_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pass_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('staff_id', sa.Uuid(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_location_id'), 'transactions', ['location_id'], unique=False)
    op.create_index(op.f('ix_transactions_pass_id'), 'transactions', ['pass_id'], unique=False)
    op.create_index(op.f('ix_transactions_staff_id'), 'transactions', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_staff_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_pass_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_location_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('staff_locations')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_index(op.f('ix_staff_brand_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_passes_user_id'), table_name='passes')
    op.drop_index(op.f('ix_passes_brand_id'), table_name='passes')
    op.drop_table('passes')
    op.drop_index(op.f('ix_locations_brand_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
